<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="WifiDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="Server.Properties.Settings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.OfflineTable" Member="OfflineTables">
    <Type Name="OfflineTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAC" Type="System.String" DbType="NChar(22) NOT NULL" CanBeNull="false" />
      <Column Name="Room" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sector" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LocationNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ApNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MapNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="X" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Y" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="RSSI" Type="System.Double" DbType="Real NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AverageOfflineTable" Member="AverageOfflineTables">
    <Type Name="AverageOfflineTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAC" Type="System.String" DbType="NChar(22) NOT NULL" CanBeNull="false" />
      <Column Name="Room" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sector" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LocationNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ApNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MapNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="X" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Y" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="RSSI" Type="System.Double" DbType="Real NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>