<?xml version="1.0" encoding="utf-8"?><Database Name="Wifi" Class="WifiDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TAREK-PC;Initial Catalog=Wifi;Persist Security Info=True;User ID=sa" SettingsObjectName="WifiLocalization.Properties.Settings" SettingsPropertyName="WifiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.OfflineMap" Member="OfflineMaps">
    <Type Name="OfflineMap">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BSSI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RSSI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="X" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Y" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ApNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocationNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MapNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Room" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sector" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>