#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WifiLocalization
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Wifi")]
	public partial class WifiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertOfflineMap(OfflineMap instance);
    partial void UpdateOfflineMap(OfflineMap instance);
    partial void DeleteOfflineMap(OfflineMap instance);
    #endregion
		
		public WifiDataContext() : 
				base(global::WifiLocalization.Properties.Settings.Default.WifiConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WifiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WifiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WifiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WifiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<OfflineMap> OfflineMaps
		{
			get
			{
				return this.GetTable<OfflineMap>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OfflineMap")]
	public partial class OfflineMap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _BSSI;
		
		private System.Nullable<int> _RSSI;
		
		private System.Nullable<double> _X;
		
		private System.Nullable<double> _Y;
		
		private System.Nullable<int> _ApNumber;
		
		private System.Nullable<int> _LocationNumber;
		
		private System.Nullable<int> _MapNumber;
		
		private System.Nullable<int> _Room;
		
		private System.Nullable<int> _Sector;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBSSIChanging(string value);
    partial void OnBSSIChanged();
    partial void OnRSSIChanging(System.Nullable<int> value);
    partial void OnRSSIChanged();
    partial void OnXChanging(System.Nullable<double> value);
    partial void OnXChanged();
    partial void OnYChanging(System.Nullable<double> value);
    partial void OnYChanged();
    partial void OnApNumberChanging(System.Nullable<int> value);
    partial void OnApNumberChanged();
    partial void OnLocationNumberChanging(System.Nullable<int> value);
    partial void OnLocationNumberChanged();
    partial void OnMapNumberChanging(System.Nullable<int> value);
    partial void OnMapNumberChanged();
    partial void OnRoomChanging(System.Nullable<int> value);
    partial void OnRoomChanged();
    partial void OnSectorChanging(System.Nullable<int> value);
    partial void OnSectorChanged();
    #endregion
		
		public OfflineMap()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSSI", DbType="NVarChar(50)")]
		public string BSSI
		{
			get
			{
				return this._BSSI;
			}
			set
			{
				if ((this._BSSI != value))
				{
					this.OnBSSIChanging(value);
					this.SendPropertyChanging();
					this._BSSI = value;
					this.SendPropertyChanged("BSSI");
					this.OnBSSIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSSI", DbType="Int")]
		public System.Nullable<int> RSSI
		{
			get
			{
				return this._RSSI;
			}
			set
			{
				if ((this._RSSI != value))
				{
					this.OnRSSIChanging(value);
					this.SendPropertyChanging();
					this._RSSI = value;
					this.SendPropertyChanged("RSSI");
					this.OnRSSIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_X", DbType="Float")]
		public System.Nullable<double> X
		{
			get
			{
				return this._X;
			}
			set
			{
				if ((this._X != value))
				{
					this.OnXChanging(value);
					this.SendPropertyChanging();
					this._X = value;
					this.SendPropertyChanged("X");
					this.OnXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y", DbType="Float")]
		public System.Nullable<double> Y
		{
			get
			{
				return this._Y;
			}
			set
			{
				if ((this._Y != value))
				{
					this.OnYChanging(value);
					this.SendPropertyChanging();
					this._Y = value;
					this.SendPropertyChanged("Y");
					this.OnYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApNumber", DbType="Int")]
		public System.Nullable<int> ApNumber
		{
			get
			{
				return this._ApNumber;
			}
			set
			{
				if ((this._ApNumber != value))
				{
					this.OnApNumberChanging(value);
					this.SendPropertyChanging();
					this._ApNumber = value;
					this.SendPropertyChanged("ApNumber");
					this.OnApNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationNumber", DbType="Int")]
		public System.Nullable<int> LocationNumber
		{
			get
			{
				return this._LocationNumber;
			}
			set
			{
				if ((this._LocationNumber != value))
				{
					this.OnLocationNumberChanging(value);
					this.SendPropertyChanging();
					this._LocationNumber = value;
					this.SendPropertyChanged("LocationNumber");
					this.OnLocationNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MapNumber", DbType="Int")]
		public System.Nullable<int> MapNumber
		{
			get
			{
				return this._MapNumber;
			}
			set
			{
				if ((this._MapNumber != value))
				{
					this.OnMapNumberChanging(value);
					this.SendPropertyChanging();
					this._MapNumber = value;
					this.SendPropertyChanged("MapNumber");
					this.OnMapNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room", DbType="Int")]
		public System.Nullable<int> Room
		{
			get
			{
				return this._Room;
			}
			set
			{
				if ((this._Room != value))
				{
					this.OnRoomChanging(value);
					this.SendPropertyChanging();
					this._Room = value;
					this.SendPropertyChanged("Room");
					this.OnRoomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sector", DbType="Int")]
		public System.Nullable<int> Sector
		{
			get
			{
				return this._Sector;
			}
			set
			{
				if ((this._Sector != value))
				{
					this.OnSectorChanging(value);
					this.SendPropertyChanging();
					this._Sector = value;
					this.SendPropertyChanged("Sector");
					this.OnSectorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
